### Numpy Mastery Assignment
- Answer all questions
- Submission : 20th September 2022

1. Create a 1D array of numbers from 0 to 9

In [1]:
import numpy as np

arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3x3 numpy of all True 

In [3]:
true_array = np.full((3, 3), True)
true_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Create an array of numbers from 20 to 39

In [4]:
arr_1 = np.arange(20,40)
arr_1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

4. Replace all odd numbers in Q3 by -1

In [5]:
arr_1 = np.arange(20,40)

arr_1[arr_1%2 != 0] = -1
arr_1

array([20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1, 36,
       -1, 38, -1])

5. Create two arrays of length 10 and print out  common items in both arrays

In [6]:
arr_2 = np.arange(10,60,5)
arr_2

arr_3 = np.arange(10,30,2)
arr_3

common_values = set(arr_2).intersection(arr_3)
common_values

{10, 20}

6.  Create a 5x5 identity matrix

In [7]:
arr_4 = np.identity(5)
arr_4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

7. In the code cell below define and print a set of arrays defined x, y and z. The array x should be take the form [10 12 9 2 20], y should have  101  values from  10  to  20  inclusive and z should be a  2×3  array of ones.

In [8]:
x = np.array([10,12,9,2,20])
x

array([10, 12,  9,  2, 20])

In [9]:
y = np.linspace(10,20,101)
y

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
       12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
       13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2, 15.3, 15.4,
       15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1, 16.2, 16.3, 16.4, 16.5,
       16.6, 16.7, 16.8, 16.9, 17. , 17.1, 17.2, 17.3, 17.4, 17.5, 17.6,
       17.7, 17.8, 17.9, 18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7,
       18.8, 18.9, 19. , 19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8,
       19.9, 20. ])

In [10]:
z = np.ones((2,3))
z

array([[1., 1., 1.],
       [1., 1., 1.]])

8.Using the available Numpy functions on array x from problem  7 , find the average and the standard deviation of the value in this array. Redefine x as an array with all these values sorted in numerical order.

In [11]:
x = np.array([10,12,9,2,20])
x

array([10, 12,  9,  2, 20])

In [12]:
np.mean(x)

10.6

In [13]:
np.std(x)

5.782732917920384

In [14]:
np.sort(x)

array([ 2,  9, 10, 12, 20])

9. Create a 10x10 array with random values and find the minimum and maximum values

In [15]:
random_array = np.random.randint(100, size =(10,10))
random_array

array([[51,  5, 82, 13, 35, 39, 42, 43,  1, 64],
       [47, 84, 15, 45, 91, 51, 78, 76, 48, 81],
       [47,  4, 28, 46, 25,  2, 80, 49, 71, 97],
       [72, 61, 69, 45, 14, 54, 13, 93, 14, 37],
       [82, 78, 46, 79, 91, 81, 12, 70, 61, 58],
       [27, 13, 34, 10, 14, 30, 71, 75, 66, 12],
       [13,  9,  2, 61, 68, 19, 81, 17, 44, 24],
       [ 1, 98, 95, 38, 79, 83, 46, 97,  4, 66],
       [80, 57, 31, 33, 54, 29, 74, 22, 32, 12],
       [73, 90, 26, 74, 40, 43, 73,  6, 12, 63]])

In [16]:
np.max(random_array)

98

In [17]:
np.min(random_array)

1

10. Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
arr_4 = np.arange(0,9)
arr_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
np.reshape(arr_4,(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

11.  Generates an array [[1 2 3] [4 5 6]]

In [20]:
arr_5 = np.array([[1,2,3], [4,5,6]])
arr_5

array([[1, 2, 3],
       [4, 5, 6]])

12. Generates an array [0 2.5 5 7.5 10]

In [21]:
arr_6 = np.array([0, 2.5, 5, 7.5, 10])
arr_6

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

13. Generates an 3x3 array of zeros

In [22]:
arr_7 = np.zeros((3,3))
arr_7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

14. Create array from 0.1 to 10 with 12 elements, inclusively

In [23]:
arr_8 = np.linspace(0.1,10,12)
arr_8

array([ 0.1,  1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1,
       10. ])

15. Create a matrix with seven columns and five rows of ten(10).

In [24]:
arr_9 = np.full((5,7), 10)
arr_9

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

16. What is the difference between numpy and list?

In [ ]:
#List can stores data of all data types but numpy stores only numerical data

17. Create a 1D array of ones consisting of  50  values. Change the values of the array so that the values alternate between ones and zeros ie  1,0,1,0,1,0,1,0,1...  ensuring that the starting value is  1 

In [25]:
arr_10 = np.ones(50)
arr_10[1::2] = 0
arr_10

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.])

18. Generate a  10×10  matrix of zeros.
Make this matrix an identity matrix

In [26]:
arr_11 = np.zeros((10,10))
arr_11

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

19. Generate an array x to be a  10×10  array of zeros. Redefine its diagonal components (from left to right) to equal one

In [27]:
arr_12 = np.zeros((10,10))
arr_12

np.fill_diagonal(arr_12, 1)
arr_12

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

20. What is the dot products of this two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [28]:
mat_1 = np.array([[1,2],[3,4]])
mat_1

array([[1, 2],
       [3, 4]])

In [29]:
mat_2 =  np.array([[5,6], [7,8]])
mat_2

array([[5, 6],
       [7, 8]])

In [30]:
np.dot(mat_1, mat_2)

array([[19, 22],
       [43, 50]])

21.  Multiply these two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [31]:
mat_A = np.array([[1,2], [3,4]])
mat_A

array([[1, 2],
       [3, 4]])

In [32]:
mat_B = np.array([[5,6], [7,8]])
mat_B

array([[5, 6],
       [7, 8]])

In [33]:
mat_A * mat_B

array([[ 5, 12],
       [21, 32]])

22. Multiply this matrix  [[1,2],[3,4]] by a  scalar value of 5

In [34]:
scalar = 5
mat_C = np.array([[1,2], [3,4]])
mat_C

array([[1, 2],
       [3, 4]])

In [35]:
scalar * mat_C

array([[ 5, 10],
       [15, 20]])

23. A = [[1,2],[3,4]] and B = transpose of A. Calculate AxB

In [36]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [37]:
B = A.transpose((1,0))
B

array([[1, 3],
       [2, 4]])

In [38]:
A * B

array([[ 1,  6],
       [ 6, 16]])

24. A= [[1,2],[3,4]] and B =  [[5,6],[7,8]]. Is A x B = B x A ? Show working

In [39]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [40]:
B = np.array([[5,6], [7,8]])
B

array([[5, 6],
       [7, 8]])

In [41]:
A * B 

array([[ 5, 12],
       [21, 32]])

In [42]:
B * A

array([[ 5, 12],
       [21, 32]])

In [50]:
A * B == B * A

array([ True,  True,  True])

25. Creates an array [[0 1 2] [3 4 5]]
- Let A = first row of the matrix
- B = second row of the matrix
- C = second column of the Matrix
- D = first row, third column of the matrix
- print A , B , C, D

In [43]:
array = np.array([[0,1,2], [3,4,5]])
array

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
A = array[0]
A

array([0, 1, 2])

In [45]:
B = array[1]
B

array([3, 4, 5])

In [46]:
C = array[:,1]
C

array([1, 4])

In [47]:
D = array[0][-1]
D

2